services:
  windows:
    build: .
    image: dockurr/windows:ghostspectre
    container_name: windows
    environment:
      VERSION: "gs11"
      VGA: "cirrus"
      # Ghost Spectre = install manual. Set saat setup: Administrator / 12345678
      # Setelah login, bat otomatis muncul di Desktop (Enable-RDP, Open-Shared, dll.)
      RAM_SIZE: "6G"
      CPU_CORES: "2"
      DISK_SIZE: "32G"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 8007:3389/tcp
      - 8007:3389/udp
    volumes:
      - ./windows:/storage
      - ./shared:/shared
      - ./oem:/oem
    restart: always
    stop_grace_period: 2m
